### ISSUE TITLE
Debugger crashes when there is no proper binary view

### ISSUE THREAD

**Issue by tur11ng** [Vector35/debugger#248]
I don't know what the expected behavior should be in this case, but I don't think it should crash the UI, maybe a simple error message or just run the binary without any support from the Binary Ninja just like running it in the terminal. The binary is called Golfer Part 1, from Hack The Box reversing challenges section.

**Comment by xusheng6** [comment]
This is a malformed ELF and the BN Elf view cannot parse it properly. The immediate reason of the crash is that we do not support using the debugger without a binary view at the moment. Related to #206

**Comment by xusheng6** [comment]
Nevertheless, the debugger should not crash and should properly handle the case.

**Comment by xusheng6** [comment]
The debugger no longer crashes with the fix. Note we choose not to directly rejecting debugging the file if the incoming binary view is a raw view. This is because, in some cases, although the binary view cannot parse it, the debugger can still debug it correctly. Although for this particular binary, LLDB also cannot debug it since it is malformed.
