### ISSUE TITLE
Crash when hitting "Connect to Process" on empty file

### ISSUE THREAD

**Issue by 0cyn** [Vector35/debugger#293]
Repro:
1. `/Applications/Binary\ Ninja.app/Contents/MacOS/plugins/lldb/bin/debugserver 127.0.0.1:8000`
2. Open BinaryNinja
3. Hit ⌘+N to create a new empty file
4. Debugger Menu -> Connect to Remote Process
5. Hit connect and see crash

**Comment by xusheng6** [comment]
Currently, trying to use the debugger without a binary view causes several issues. This will be addressed by #206

**Comment by xusheng6** [comment]
The immediate crash is fixed by 9f26464cacea1cee81842c2bade152c2653fb045. However, I am leaving this issue open because there are still many other ways to crash the debugger in such a non-working scenario. Most of them are missing nullptr checks. 

I am moving this out of the milestone because it is no super urgent to fix

**Comment by xusheng6** [comment]
I am closing this because https://github.com/Vector35/debugger/issues/206 tracks the remaining issue and this one adds no extra value
