### ISSUE TITLE
Can't build the project - some binaryninja-api functions are missing

### ISSUE THREAD

**Issue by dzervas** [Vector35/debugger#490]
I'm trying to build the project locally -  I want to expose some C++ methods in python (DebugAdapter, more methods of DebugAdapterType and more)

The `build.md` doesn't seem to be accurate as `cmake` doesn't find anything if executed inside the build dir
Also, when I:
```
cmake -DBN_API_PATH=/home/dzervas/Lab/binaryninja-api -DBN_INSTALL_DIR=/opt/binaryninja -DLLVM_VERSION=14.0.0 ..
make
```

I get the following error:
```
[ 74%] Linking CXX executable debugger_generator
/usr/bin/ld: ../../core/api/out/libbinaryninjaapi.a(binaryview.cpp.o): in function `BinaryNinja::BinaryView::GetFullStringSize(unsigned long, BNStringType)':
binaryview.cpp:(.text+0x11f1b): undefined reference to `BNGetFullStringSize'
/usr/bin/ld: ../../core/api/out/libbinaryninjaapi.a(filemetadata.cpp.o): in function `BinaryNinja::FileMetadata::RevertUndoActions(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
filemetadata.cpp:(.text+0x13b8): undefined reference to `BNRevertUndoActions'
/usr/bin/ld: ../../core/api/out/libbinaryninjaapi.a(binaryninjaapi.cpp.o): in function `BinaryNinja::WorkerEnqueue(std::function<void ()> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
binaryninjaapi.cpp:(.text+0x11a1): undefined reference to `BNWorkerEnqueueNamed'
/usr/bin/ld: ../../core/api/out/libbinaryninjaapi.a(binaryninjaapi.cpp.o): in function `BinaryNinja::WorkerPriorityEnqueue(std::function<void ()> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
binaryninjaapi.cpp:(.text+0x1443): undefined reference to `BNWorkerPriorityEnqueueNamed'
/usr/bin/ld: ../../core/api/out/libbinaryninjaapi.a(binaryninjaapi.cpp.o): in function `BinaryNinja::WorkerInteractiveEnqueue(std::function<void ()> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
binaryninjaapi.cpp:(.text+0x16e5): undefined reference to `BNWorkerInteractiveEnqueueNamed'
/usr/bin/ld: ../../core/api/out/libbinaryninjaapi.a(database.cpp.o): in function `BinaryNinja::Snapshot::GetUndoData()':
database.cpp:(.text+0x1506): undefined reference to `BNGetSnapshotUndoData'
collect2: error: ld returned 1 exit status
make[2]: *** [api/python/CMakeFiles/debugger_generator.dir/build.make:99: api/python/debugger_generator] Error 1
make[1]: *** [CMakeFiles/Makefile2:268: api/python/CMakeFiles/debugger_generator.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```

Total guess but I think that it mixes code from the production installed lib and the dev branch of the cloned binaryninja-api

**Comment by xusheng6** [comment]
You will need a dev build of binary ninja and checkout the binaryninja-api to the corresponding commit. 

1. You can update binary ninja to the development build following this guide: https://docs.binary.ninja/guide/index.html#support
2. Checkout api repo. There are two ways to do it: if you downloaded the latest dev, then you can checkout the api repo to the latest dev as well. A more robust approach is to find the file `api_REVISION.txt` in `BN_INSTALLATION_FOLDER/Resources`, which should contain something similar to:
```
API repository revision https://github.com/Vector35/binaryninja-api/tree/9f1ded021920a3187250e18fe08c7457be4417dd
```

3. Right now we are building the debugger with LLDB-16.0.0. I have updated the release page at: https://github.com/Vector35/lldb-artifacts
4. I suggest you hop into our slack https://slack.binary.ninja/ so that I can better assist you with the build should you run into any further issues. And we can better coordinate if you are interested in contributing code (thx!)

**Comment by xusheng6** [comment]
Related to https://github.com/Vector35/debugger/issues/357
