### ISSUE TITLE
Support debugging x64 binaries running inside arm64 Windows

### ISSUE THREAD

**Issue by dmeledon** [Vector35/debugger#523]
I’m getting “[Default] Failed to init an adapter of type DBGENG” when I attempt to run the debugger.

I see C:\Windows\XtaCache\DBGHELP.DLL.B3879D9F5BB2208728DD7FDE7F4A8E7B.C567476C4CBBB5D33DD9C048ADDDD873.x64.mp.1.jc and C:\Users\dit\windbgx\amd64\dbghelp.dll as the loaded DLLs for binaryninja.exe.

In this particular case I'm running Windows 11 Pro 23H2 in Parallels Pro 19.2 on MacOS 14.1.1 using an Apple Silicon MacBook Pro.

**Comment by xusheng6** [comment]
This works since 4.1.5356-dev. Note Windows on Arm is not an officially supported platform, and running the x64 version of binja under emulation could cause certain bugs. That said, debugging generally works, with the only noticeable issue being that the step over always result in a step into. I am closing this issue as completed and we may file new ones when we find issues regarding debugging in WoA
